name: app_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  shared_preferences: ^2.5.3
  pin_code_fields: ^8.0.1
  flutter_screenutil: ^5.9.3
  page_flip: ^0.2.5+1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  get: ^4.6.5
  flutter_secure_storage: ^9.2.2
  get_it: ^7.6.4
  image_picker: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/image/
