name: app_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+11

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # Basic UI
  cupertino_icons: ^1.0.8
  provider: ^6.1.1
  country_code_picker: ^2.0.2
  
  # Storage
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.2
  
  # Network
  dio: ^5.9.0
  
  # State Management
  flutter_bloc: ^9.1.1
  
  # Navigation
  get: ^4.6.5
  
  # Dependency Injection
  get_it: ^7.6.4
  
  # Media
  image_picker: ^1.0.7
  
  # UI Components
  pin_code_fields: ^8.0.1
  flutter_screenutil: ^5.9.3
  page_flip: ^0.2.5+1
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  
  # Splash & Icons
  flutter_native_splash: ^2.3.7
  flutter_launcher_icons: ^0.13.1
  
  # Real-time & WebSocket

  
  # Cached Images
  cached_network_image: ^3.3.0
  
  # Pusher/Pusher Echo Alternative
  # laravel_echo: ^1.1.0
  pusher_client_fixed: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/image/